name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  PGUSER: postgres
  PGPASSWORD: postgres
  PGHOST: localhost
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.FF_BE_MASTER_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Prepare the environment.
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Cache Ruby dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install PostgreSQL client
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: ./installer-deps.sh

      # Run the checks.
      - name: Run the formatter, linters, and static analysers
        run: bundle exec rubocop
      - name: Run the security static analyser
        run: bundle exec bundler-audit check --update
      - name: Run vulnerability scanner
        run: bundle exec brakeman -q -w2
      - name: Build the documentation
        run: bundle exec yardoc 'lib/**/*.rb' 'app/**/*.rb'

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Prepare the environment.
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Cache Ruby dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install PostgreSQL client
        run: sudo apt-get install libpq-dev
      - name: Set up the project
        run: ./installer.sh
      - name: Run tests
        run: bundle exec rspec
      - name: Publish test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: .github/codecov.yml

  release:
    needs:
      - check
      - test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Install release tools
        run: |
          mkdir -p bin
          echo "::add-path::$GITHUB_WORKSPACE/bin"
          curl -sLO https://github.com/rgreinho/keeparelease/releases/download/1.1.2/keeparelease-1.1.2-linux-amd64
          chmod a+x keeparelease-1.1.2-linux-amd64
          mv keeparelease-1.1.2-linux-amd64 bin/keeparelease
      - name: Prepare release content
        run: keeparelease -x > ${{ github.workflow }}-release.md
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workflow }}-release.md
