name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          PGUSER: postgres
          PGPASSWORD: ""
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Prepare the environment.
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.3"
      - name: Install tools
        run: |
          mkdir -p bin
          echo "::add-path::$GITHUB_WORKSPACE/bin"
          curl -sLO https://github.com/rgreinho/keeparelease/releases/download/1.1.2/keeparelease-1.1.2-linux-amd64
          chmod a+x keeparelease-1.1.2-linux-amd64
          mv keeparelease-1.1.2-linux-amd64 bin/keeparelease

      # Install and chache the dependencies.
      - name: Cache Ruby dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Node Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install the project.
      - name: Install PostgreSQL client
        # Required to compile pg ruby gem.
        run: sudo apt-get install libpq-dev
      - name: Set up the project
        env:
          FF_BE_MASTER_KEY: ${{ secrets.FF_BE_MASTER_KEY }}
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: ""
        run: ./installer.sh

      # Run the checks.
      - name: Run the formatter, linters, and static analysers
        run: bundle exec rubocop
      - name: Run the security static analyser
        run: bundle exec bundler-audit check --update
      - name: Run vulnerability scanner
        run: bundle exec brakeman -q -w2
      - name: Build the documentation
        run: bundle exec yardoc 'lib/**/*.rb' 'app/**/*.rb'
      - name: Run tests
        env:
          PGUSER: postgres
        run: bundle exec rspec

      # Publish rspec results
      - name: Publish test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: .github/codecov.yml

      # Prepare the release artifacts.
      - name: Prepare release content
        run: keeparelease -x > ${{ github.workflow }}-release.md

        # Publish a new release when a tag is created.
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workflow }}-release.md
